@ECHO OFF
REM * Allows user to write their own files at the DOS screen prompt: 'C:\>'...
REM * and, store the characters into any: 'filename.filenameExtension'
copy con "test.txt"
REM * After which command you will see a ... prompt; where you can type in each line of text...
REM * keep on pressing [ENTER] key to start a new line...
REM * when done, press [CTRL] + [Z] to end typing in the file contents.
