@ECHO OFF
REM *** Example 1: Delete a single file...with a specific filename, and, a specific filename extension...
DEL filename.ext
REM *** Example 2: Delete ALL [.txt] extension files...
DEL *.txt
REM *** Example 3: Delete ALL [.txt] extension files beginning with letter: h...
DEL h*.txt
REM *** Example 4: Delete ALL files...including any filename:(*)/any filename extension:(*)...
DEL *.*
