@ECHO OFF
ECHO MAIN TITLE TEXT
ECHO.
ECHO Table Of Contents:-
ECHO.
ECHO 1: SUB TITLE TEXT ONE
ECHO 2: SUB TITLE TEXT TWO
ECHO 3: SUB TITLE TEXT THREE
ECHO.
PAUSE
REM *** load the next page...
pageA1.bat

